-- Master tables

CREATE TABLE IF NOT EXISTS master.financial_year_master (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    financial_year varchar(9) NOT NULL UNIQUE,
    fy_code varchar(4) NOT NULL UNIQUE,
    is_active boolean DEFAULT false,
    created_at timestamp DEFAULT now()
);

COMMENT ON TABLE master.financial_year_master IS 'Financial years (e.g., 2024-2025)';
COMMENT ON COLUMN master.financial_year_master.fy_code IS 'Short code like 2425 for partition naming';

CREATE TABLE IF NOT EXISTS master.treasury (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treasury_code varchar(3) UNIQUE NOT NULL,
    treasury_name varchar(100) NOT NULL,
    is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS master.ddo (
    ddo_code varchar(9) PRIMARY KEY,
    ddo_name varchar(200) NOT NULL,
    is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS master.department (
    dept_code varchar(10) PRIMARY KEY,
    dept_name varchar(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS master.rbi_ifsc_stock (
    id serial PRIMARY KEY,
    ifsc_code varchar(11) UNIQUE NOT NULL,
    bank_name varchar(100),
    branch_name varchar(100)
);

CREATE TABLE IF NOT EXISTS master.active_hoa_mst (
    id serial PRIMARY KEY,
    demand varchar(2),
    major_head varchar(4),
    sub_major_head varchar(2),
    minor_head varchar(3),
    plan_status varchar(2),
    scheme_head varchar(3),
    detail_head varchar(2),
    voted_charged varchar(1),
    hoa_description varchar(500),
    is_active boolean DEFAULT true
);
