-- Billing master tables

CREATE TABLE IF NOT EXISTS billing_master.bill_status_master (
    status_id smallint PRIMARY KEY,
    status_name varchar(50) NOT NULL,
    status_description varchar(200)
);

CREATE TABLE IF NOT EXISTS billing_master.tr_master (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tr_name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS billing_master.bt_details (
    bt_serial smallint PRIMARY KEY,
    bt_type_name varchar(100) NOT NULL,
    is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS billing_master.cpin_master (
    id serial PRIMARY KEY,
    cpin_number varchar(20) UNIQUE NOT NULL,
    cpin_date date,
    amount bigint
);
