-- =============================================================================
-- Partitioned Tables with EF Core-Compatible Identity Columns
-- Using GENERATED BY DEFAULT instead of GENERATED ALWAYS for scaffolding support
-- =============================================================================

-- Bill Details (Parent Table)
CREATE TABLE IF NOT EXISTS billing.bill_details
(
    bill_id bigint GENERATED BY DEFAULT AS IDENTITY,
    bill_no character(15),
    bill_date date NOT NULL,
    bill_mode smallint,
    reference_no character varying(20),
    tr_master_id smallint NOT NULL,
    payment_mode smallint NOT NULL,
    financial_year smallint NOT NULL,
    demand character(2),
    major_head character(4),
    sub_major_head character(2),
    minor_head character(3),
    ddo_code character(9),
    treasury_code character(3),
    gross_amount bigint DEFAULT 0,
    net_amount bigint DEFAULT 0,
    bt_amount bigint DEFAULT 0,
    status smallint NOT NULL DEFAULT 1,
    is_deleted boolean NOT NULL DEFAULT false,
    is_gst boolean DEFAULT false,
    gst_amount bigint DEFAULT 0,
    plan_status character(2),
    scheme_head character(3),
    detail_head character(2),
    voted_charged character(1),
    remarks character varying(100),
    sanction_no character varying(50),
    sanction_by character varying(100),
    created_by_userid bigint,
    created_at timestamp DEFAULT now(),
    updated_by_userid bigint,
    updated_at timestamp,
    PRIMARY KEY (bill_id, financial_year),
    FOREIGN KEY (financial_year) REFERENCES master.financial_year_master(id)
) PARTITION BY LIST (financial_year);

COMMENT ON TABLE billing.bill_details IS 'Bill details parent table - partitioned by financial_year';

-- Bill BT Details
CREATE TABLE IF NOT EXISTS billing.bill_btdetail
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    bill_id bigint NOT NULL,
    financial_year smallint NOT NULL,
    bt_serial smallint,
    amount bigint,
    ddo_code character(9),
    treasury_code character(3),
    created_by_userid bigint,
    created_at timestamp DEFAULT now(),
    updated_by_userid bigint,
    updated_at timestamp,
    PRIMARY KEY (id, financial_year),
    FOREIGN KEY (bill_id, financial_year) REFERENCES billing.bill_details(bill_id, financial_year) ON DELETE CASCADE,
    FOREIGN KEY (financial_year) REFERENCES master.financial_year_master(id)
) PARTITION BY LIST (financial_year);

-- Bill GST Details
CREATE TABLE IF NOT EXISTS billing.bill_gst
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    bill_id bigint NOT NULL,
    financial_year smallint NOT NULL,
    cpin_id integer,
    ddo_gstn character varying(15),
    created_by_userid bigint,
    created_at timestamp DEFAULT now(),
    updated_by_userid bigint,
    updated_at timestamp,
    PRIMARY KEY (id, financial_year),
    FOREIGN KEY (bill_id, financial_year) REFERENCES billing.bill_details(bill_id, financial_year) ON DELETE CASCADE,
    FOREIGN KEY (financial_year) REFERENCES master.financial_year_master(id)
) PARTITION BY LIST (financial_year);

-- Bill ECS/NEFT Details
CREATE TABLE IF NOT EXISTS billing.bill_ecs_neft_details
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    bill_id bigint NOT NULL,
    financial_year smallint NOT NULL,
    payee_name character varying(200),
    ifsc_code character(11),
    bank_account_number character varying(20),
    amount bigint,
    beneficiary_id integer,
    pan_no character varying(10),
    contact_number character varying(15),
    address character varying(500),
    email character varying(100),
    bank_name character varying(100),
    created_by_userid bigint,
    created_at timestamp DEFAULT now(),
    updated_by_userid bigint,
    updated_at timestamp,
    PRIMARY KEY (id, financial_year),
    FOREIGN KEY (bill_id, financial_year) REFERENCES billing.bill_details(bill_id, financial_year) ON DELETE CASCADE,
    FOREIGN KEY (financial_year) REFERENCES master.financial_year_master(id)
) PARTITION BY LIST (financial_year);

-- DDO Allotment Booked Bill
CREATE TABLE IF NOT EXISTS billing.ddo_allotment_booked_bill
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    bill_id bigint NOT NULL,
    financial_year smallint NOT NULL,
    allotment_id integer,
    amount bigint NOT NULL,
    active_hoa_id integer NOT NULL,
    ddo_code character(9),
    treasury_code character(3),
    created_by_userid bigint,
    created_at timestamp DEFAULT now(),
    updated_by_userid bigint,
    updated_at timestamp,
    PRIMARY KEY (id, financial_year),
    FOREIGN KEY (bill_id, financial_year) REFERENCES billing.bill_details(bill_id, financial_year) ON DELETE CASCADE,
    FOREIGN KEY (financial_year) REFERENCES master.financial_year_master(id),
    FOREIGN KEY (active_hoa_id) REFERENCES master.active_hoa_mst(id)
) PARTITION BY LIST (financial_year);

-- Bill Subvoucher
CREATE TABLE IF NOT EXISTS billing.bill_subvoucher
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    bill_id bigint NOT NULL,
    financial_year smallint NOT NULL,
    subvoucher_no character varying(50),
    subvoucher_date date,
    subvoucher_amount bigint,
    description character varying(200),
    created_by_userid bigint,
    created_at timestamp DEFAULT now(),
    updated_by_userid bigint,
    updated_at timestamp,
    PRIMARY KEY (id, financial_year),
    FOREIGN KEY (bill_id, financial_year) REFERENCES billing.bill_details(bill_id, financial_year) ON DELETE CASCADE,
    FOREIGN KEY (financial_year) REFERENCES master.financial_year_master(id)
) PARTITION BY LIST (financial_year);

-- Note: Using GENERATED BY DEFAULT instead of GENERATED ALWAYS
-- This makes the identity columns compatible with EF Core scaffolding
-- Foreign keys use composite (bill_id, financial_year) for referential integrity
