using Microsoft.EntityFrameworkCore;
using PartitionTableFullStack.API.Models;

namespace PartitionTableFullStack.API.Data;

/// <summary>
/// Partial class extending ApplicationDbContext with partitioned billing tables.
/// This file is AUTO-GENERATED by scaffold-models.ps1 - do not edit manually.
/// 
/// WHY PARTIAL CLASS?
/// - EF Core scaffolding cannot handle PostgreSQL partitioned tables
/// - When scaffolding runs, it regenerates ApplicationDbContext.cs but NOT this file
/// - This allows us to maintain billing tables while keeping scaffolding for regular tables
/// </summary>
public partial class ApplicationDbContext
{
    // DbSets for partitioned billing tables
    public virtual DbSet<BillBtdetail> BillBtdetail { get; set; }
    public virtual DbSet<BillDetails> BillDetails { get; set; }
    public virtual DbSet<BillEcsNeftDetails> BillEcsNeftDetails { get; set; }
    public virtual DbSet<BillGst> BillGst { get; set; }
    public virtual DbSet<BillSubvoucher> BillSubvoucher { get; set; }
    public virtual DbSet<DdoAllotmentBookedBill> DdoAllotmentBookedBill { get; set; }

    /// <summary>
    /// Configure billing tables - PKs, FKs, indexes auto-generated from database schema
    /// Called from main OnModelCreating via OnModelCreatingPartial
    /// </summary>
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
        // BillBtdetail
        modelBuilder.Entity<BillBtdetail>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.FinancialYear });
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.FinancialYear);
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.BillId);
            entity.HasOne<FinancialYearMaster>().WithMany().HasForeignKey(e => e.FinancialYear);
        });
        // BillDetails
        modelBuilder.Entity<BillDetails>(entity =>
        {
            entity.HasKey(e => new { e.BillId, e.FinancialYear });
            entity.Property(e => e.BillId).ValueGeneratedOnAdd();
            entity.HasOne<FinancialYearMaster>().WithMany().HasForeignKey(e => e.FinancialYear);
        });
        // BillEcsNeftDetails
        modelBuilder.Entity<BillEcsNeftDetails>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.FinancialYear });
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.FinancialYear);
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.BillId);
            entity.HasOne<FinancialYearMaster>().WithMany().HasForeignKey(e => e.FinancialYear);
        });
        // BillGst
        modelBuilder.Entity<BillGst>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.FinancialYear });
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.FinancialYear);
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.BillId);
            entity.HasOne<FinancialYearMaster>().WithMany().HasForeignKey(e => e.FinancialYear);
        });
        // BillSubvoucher
        modelBuilder.Entity<BillSubvoucher>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.FinancialYear });
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.FinancialYear);
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.BillId);
            entity.HasOne<FinancialYearMaster>().WithMany().HasForeignKey(e => e.FinancialYear);
        });
        // DdoAllotmentBookedBill
        modelBuilder.Entity<DdoAllotmentBookedBill>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.FinancialYear });
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.FinancialYear);
            entity.HasOne<ActiveHoaMst>().WithMany().HasForeignKey(e => e.ActiveHoaId);
            entity.HasOne<BillDetails>().WithMany().HasForeignKey(e => e.BillId);
            entity.HasOne<FinancialYearMaster>().WithMany().HasForeignKey(e => e.FinancialYear);
        });
    }
}
